name: Deploy Portfolio al Servidor

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copiar archivos via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          target: "/www/laravel"

      - name: Ejecutar comandos remoto via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /www/laravel
            docker exec -it app bash -c "composer install --no-dev"
            docker exec -it app bash -c "npm install --production"
            docker exec -it app bash -c "php artisan migrate --force"
            docker exec -it app bash -c "php artisan optimize:clear"
            docker exec -it app bash -c "php artisan optimize"
