name: Deploy Portfolio al Servidor

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copiar archivos via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: "./"
          target: "/home/migbert/www/laravel"

      - name: Ejecutar comandos remoto via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script_stop: true
          script: |
            cd /www/laravel
            cp .env.example .env
            docker exec app bash -c "composer install --no-dev --no-progress -a"
            docker exec app bash -c "npm install"
            docker exec app bash -c "npm run build"
            docker exec app bash -c "php artisan migrate:fresh --seed"
            docker exec app bash -c "php artisan storage:link"
            docker exec app bash -c "php artisan lang:update"
            docker exec app bash -c "php artisan optimize"
